apiVersion: v1
kind: ConfigMap
metadata:
  name: uas-todo-db-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS todos (
      id SERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      completed BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
