apiVersion: apps/v1
kind: Deployment
metadata:
  name: uas-todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uas-todo-frontend
  template:
    metadata:
      labels:
        app: uas-todo-frontend
    spec:
      containers:
        - name: uas-todo-frontend
          image: uas-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: uas-todo-frontend
spec:
  type: NodePort
  selector:
    app: uas-todo-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
