apiVersion: apps/v1
kind: Deployment
metadata:
  name: uas-todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uas-todo-db
  template:
    metadata:
      labels:
        app: uas-todo-db
    spec:
      containers:
        - name: uas-todo-db
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: uas-todo-db-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uas-todo-db-secrets
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: uas-todo-db-secrets
                  key: dbname
          volumeMounts:
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-init
          configMap:
            name: uas-todo-db-init-script
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: uas-todo-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: uas-todo-db
spec:
  selector:
    app: uas-todo-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uas-todo-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
